#version: "3.3"

services:
  jupyter:  # you can change this to whatever you want.
    container_name: computer-vison
    image: tensorflow/tensorflow:2.7.0-gpu-jupyter
    volumes:
      - "./:/tf/notebooks"
    ports:
     - "8888:8888"
     - "6006:6006"
     - "6008:6008"
    deploy:
      resources:
        reservations:
          devices:
          -  driver: nvidia
             count: all
             capabilities: [gpu]
 
